### ISSUE TITLE
Add calculation on the Enter/Return

### ISSUE THREAD

**Issue by pavelbinar** [zdenekpribyla/gas-calculator#4]
Display result when the user hits the Enter/Return on the keyboard.

**Comment by zdenekpribyla** [comment]
zkoušel jsem přes dvě hodiny, ale nedám to v této fázi.
početl jsem co se dalo a bude zřejmě něco
if aktivuje keycode ===13 {
aktivuj kliknutí na 'button-click' }
doladime ve stredu

**Comment by pavelbinar** [comment]
```javascript
document.querySelector('#txtSearch').addEventListener('keypress', function (e) {
    var key = e.which || e.keyCode;
    if (key === 13) { // 13 is enter
      // code for enter
    }
});
```

Source: https://stackoverflow.com/questions/14542062/eventlistener-enter-key
