### ISSUE TITLE
Use font widely used and available on all major platforms

### ISSUE THREAD

**Issue by pavelbinar** [zdenekpribyla/gas-calculator#7]
https://github.com/zdenekpribyla/test-project/blob/2511705a126ae3161c1801acab9be53a9b552a0c/styles.css#L13

Use some standard font which is on all platforms (Mac, Linux, Windows) or use some of the Web Fonts like https://fonts.google.com/

This is how the app looks like on Mac OSX `10.12.6`

<img width="568" alt="screenshot 2017-08-20 13 29 53" src="https://user-images.githubusercontent.com/1060032/29494496-bdbebb9e-85ab-11e7-88e8-f6da294d6474.png">

**Comment by zdenekpribyla** [comment]
change to widely used sans-serif
